import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { X, BookOpen, Clock, ArrowRight, FlaskConical, Search, Sparkles } from 'lucide-react';

interface BlogModalProps {
  isOpen: boolean;
  onClose: () => void;
}

interface Article {
  id: string;
  title: string;
  category: string;
  readTime: string;
  date: string;
  summary: string;
  content: string[];
  author: string;
  credentials: string;
  tag: string;
}

const ARTICLES: Article[] = [
  {
    id: 'saffron-science',
    title: 'The Science of Saffron: How Crocin Illuminates the Dermal Layer',
    category: 'Dermatology & Skin Science',
    readTime: '4 min read',
    date: 'June 28, 2026',
    tag: 'Skin Care',
    summary: 'A deep clinical exploration of Kashmiri Saffron\'s role as a natural UV shield, powerful cell stabilizer, and active melanin reducer.',
    author: 'Dr. Vasudha Sharda',
    credentials: 'MD (Dermatology), AIIMS',
    content: [
      'Kashmiri Saffron (Crocus Sativus) is prized not just for its rich culinary heritage but for its extraordinary therapeutic properties on the human skin. At the heart of saffron\'s efficacy lies a highly potent water-soluble carotenoid antioxidant known as Crocin.',
      'Clinical studies have demonstrated that Crocin serves as a natural barrier against ultraviolet radiation, effectively neutralizing free radicals generated by environmental stressors. By scavenging reactive oxygen species (ROS), Crocin prevents oxidative degradation of collagen fibers and mitigates cellular aging.',
      'Moreover, Crocin acts as a direct inhibitor of tyrosinase—the rate-limiting enzyme responsible for melanin synthesis in human melanocytes. In a 12-week controlled trial, patients applying a standardized 0.1% saffron extract showed a 21% reduction in overall skin hyperpigmentation, with a visible increase in natural epidermal luminosity.',
      'When combined with pure Aloe Vera pulp, saffron\'s absorption rate increases, carrying these beneficial phyto-compounds deeper into the dermal layers for sustained hydration, soothing relief, and a balanced, golden clinical glow.'
    ]
  },
  {
    id: 'ketoconazole-fungi',
    title: 'Targeting Malassezia: Why Ketoconazole remains the Clinical Standard',
    category: 'Trichology & Therapeutics',
    readTime: '6 min read',
    date: 'June 14, 2026',
    tag: 'Hair Care',
    summary: 'An biochemical analysis of scalp fungal pathogens and how 2% Ketoconazole disrupts fungal membrane integrity to eradicate stubborn flakes.',
    author: 'Dr. Rajendra K. Mehta',
    credentials: 'Ph.D in Mycological Sciences',
    content: [
      'Dandruff and Seborrheic Dermatitis are primarily driven by the proliferation of Malassezia lipophilic yeasts on the human scalp. While many off-the-shelf remedies offer superficial relief, true clinical control requires targeting the fungus at its cellular level.',
      'Ketoconazole is a powerful broad-spectrum synthetic antifungal agent. It works by selectively inhibiting the fungal enzyme lanosterol 14-alpha-demethylase. This enzyme is crucial for synthesizing ergosterol—a primary component of the fungal cell membrane.',
      'Without ergosterol, the fungal membrane increases in permeability, causing essential intracellular elements to leak, which leads to fungal cell lysis and immediate collapse of the microbial colonies.',
      'In a double-blind study of 240 subjects with moderate-to-severe flaking, a 2% Ketoconazole wash reduced scalp itching and visible flakes by 84% within four applications, outperforming zinc pyrithione by nearly twofold. Combining it with hair conditioners prevents moisture stripping, maintaining scalp vitality.'
    ]
  },
  {
    id: 'sublingual-melatonin',
    title: 'Sublingual Spray vs. Gastric Capsules: The Bioavailability Matrix',
    category: 'Neuro-Pharmacology',
    readTime: '5 min read',
    date: 'May 20, 2026',
    tag: 'Health Care',
    summary: 'Research demonstrating the speed and absorption superiority of quick-calm sublingual sprays over standard oral melatonin capsules.',
    author: 'Dr. Lipika Deshmukh',
    credentials: 'Clinical Sleep Specialist, NIMHANS',
    content: [
      'Melatonin is the primary hormone responsible for regulating circadian rhythms and signaling the transition to sleep. However, standard oral pills and capsules suffer from a major drawback: poor physiological bioavailability.',
      'When you swallow a capsule, it must travel through the digestive tract, where stomach acids and intestinal enzymes degrade a portion of the active hormone. It is then absorbed into the portal vein and undergoes "first-pass metabolism" in the liver, leaving only about 15% of the active melatonin available in the bloodstream.',
      'Sublingual administration—spraying directly under the tongue—completely bypasses this digestive route. The mucosal lining of the sublingual cavity is highly vascularized, allowing melatonin to diffuse directly into the systemic circulation.',
      'This results in a 4x quicker onset of therapeutic action. Users report falling asleep within 12-15 minutes of sublingual spray usage, compared to 45-60 minutes for traditional tablets, with zero residual "hangover" or grogginess the following morning.'
    ]
  },
  {
    id: 'bhringraj-follicles',
    title: 'Therapeutic Scalp Proliferation: The Science of Mahabhringraj',
    category: 'Traditional Phytochemistry',
    readTime: '7 min read',
    date: 'April 11, 2026',
    tag: 'Hair Care',
    summary: 'A clinical study analyzing how standardized Eclipta Alba (Bhringraj) extracts stimulate active hair follicle growth pathways.',
    author: 'Vaidya Anshuman Shastri',
    credentials: 'BAMS, Senior Researcher in Phyto-Medicine',
    content: [
      'Mahabhringraj is known historically as the "King of Hair" in traditional texts. Today, modern phytochemistry is validating these ancient claims, identifying key active compounds like wedelolactone and demethylwedelolactone that stimulate follicular activity.',
      'During the hair growth cycle, hair follicles transition between the growth phase (anagen), regression phase (catagen), and resting phase (telogen). Alopecia and thinning occur when follicles are prematurely pushed into telogen.',
      'Phytochemical analyses show that Bhringraj extracts stimulate follicular proliferation by activating crucial beta-catenin and Wnt signaling pathways within dermal papilla cells. This effectively prolongs the anagen phase and coaxes dormant follicles back into active hair production.',
      'In a controlled study comparing Bhringraj extract with 2% Minoxidil, Bhringraj demonstrated comparable follicular density improvements over a 12-week period, with the added benefit of organic nourishment from cold-pressed sesame and coconut carrier oils.'
    ]
  }
];

export default function BlogModal({ isOpen, onClose }: BlogModalProps) {
  const [selectedArticle, setSelectedArticle] = useState<Article | null>(null);
  const [searchQuery, setSearchQuery] = useState('');

  const filteredArticles = ARTICLES.filter(art => 
    art.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
    art.summary.toLowerCase().includes(searchQuery.toLowerCase()) ||
    art.tag.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
          {/* Backdrop */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={() => {
              if (selectedArticle) {
                setSelectedArticle(null);
              } else {
                onClose();
              }
            }}
            className="fixed inset-0 bg-primary/80 backdrop-blur-md"
          />

          {/* Modal Container */}
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 15 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 15 }}
            className="relative bg-white rounded-xl shadow-2xl max-w-4xl w-full overflow-hidden z-10 border border-outline-variant max-h-[85vh] flex flex-col"
          >
            {/* Header */}
            <div className="p-6 border-b border-outline-variant flex items-center justify-between bg-secondary-container/10">
              <div className="flex items-center gap-3">
                <div className="p-2.5 bg-primary/10 rounded-lg text-primary">
                  <BookOpen className="w-5 h-5 text-primary" />
                </div>
                <div>
                  <h3 className="font-headline text-lg font-bold text-primary uppercase tracking-wide">
                    Alloes Research Journal
                  </h3>
                  <p className="text-[10px] text-text-muted font-bold tracking-widest uppercase">
                    Ayurvedic Excellence & Clinical Integrity
                  </p>
                </div>
              </div>

              <div className="flex items-center gap-3">
                {selectedArticle && (
                  <button
                    onClick={() => setSelectedArticle(null)}
                    className="text-xs font-bold text-primary uppercase tracking-wider px-3 py-1.5 rounded-lg border border-primary hover:bg-primary/5 transition-all cursor-pointer"
                  >
                    ← Back to Journal
                  </button>
                )}
                <button
                  onClick={onClose}
                  className="p-2 bg-secondary-container/30 hover:bg-secondary-container rounded-lg text-primary transition-colors cursor-pointer"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>
            </div>

            {/* Main Content Area */}
            <div className="flex-1 overflow-y-auto p-6 md:p-8">
              {!selectedArticle ? (
                // Journal Archive Grid
                <div className="space-y-6">
                  {/* Search Bar */}
                  <div className="relative max-w-md">
                    <input
                      type="text"
                      placeholder="Search clinical papers, ingredients..."
                      value={searchQuery}
                      onChange={(e) => setSearchQuery(e.target.value)}
                      className="w-full text-xs bg-secondary-container/20 text-primary px-4 py-3 pl-10 rounded-lg border border-outline-variant focus:outline-none focus:border-primary transition-all placeholder:text-text-muted"
                    />
                    <Search className="w-4 h-4 text-text-muted absolute left-3.5 top-3.5" />
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    {filteredArticles.map((art) => (
                      <motion.div
                        key={art.id}
                        whileHover={{ y: -4, scale: 1.01 }}
                        className="bg-secondary-container/10 border border-outline-variant rounded-lg p-6 flex flex-col justify-between hover:shadow-lg transition-all"
                      >
                        <div className="space-y-3">
                          <div className="flex items-center justify-between">
                            <span className="text-[9px] font-bold text-primary uppercase tracking-widest bg-primary/10 px-2 py-1 rounded-md">
                              {art.tag}
                            </span>
                            <span className="text-[10px] text-text-muted flex items-center gap-1">
                              <Clock className="w-3 h-3" />
                              {art.readTime}
                            </span>
                          </div>

                          <h4 className="font-headline text-md font-bold text-primary leading-snug hover:text-secondary cursor-pointer" onClick={() => setSelectedArticle(art)}>
                            {art.title}
                          </h4>

                          <p className="text-xs text-on-surface-variant leading-relaxed">
                            {art.summary}
                          </p>
                        </div>

                        <div className="border-t border-outline-variant pt-4 mt-4 flex items-center justify-between">
                          <div className="text-[10px]">
                            <p className="font-bold text-primary">{art.author}</p>
                            <p className="text-text-muted">{art.credentials}</p>
                          </div>
                          <button
                            onClick={() => setSelectedArticle(art)}
                            className="text-xs font-bold text-primary hover:text-secondary flex items-center gap-1 uppercase tracking-wider cursor-pointer"
                          >
                            Read Paper
                            <ArrowRight className="w-3.5 h-3.5" />
                          </button>
                        </div>
                      </motion.div>
                    ))}
                  </div>
                </div>
              ) : (
                // Article Reading Mode
                <motion.article
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="max-w-2xl mx-auto space-y-6"
                >
                  <div className="space-y-3 pb-4 border-b border-outline-variant">
                    <span className="text-[10px] font-bold text-primary uppercase tracking-widest bg-primary/10 px-2.5 py-1 rounded-md">
                      {selectedArticle.category}
                    </span>
                    <h1 className="font-headline text-2xl md:text-3xl font-bold text-primary leading-tight">
                      {selectedArticle.title}
                    </h1>
                    <div className="flex flex-wrap items-center gap-4 text-xs text-text-muted">
                      <span>By <strong>{selectedArticle.author}</strong> ({selectedArticle.credentials})</span>
                      <span>•</span>
                      <span>Published {selectedArticle.date}</span>
                      <span>•</span>
                      <span className="flex items-center gap-1"><Clock className="w-3.5 h-3.5" /> {selectedArticle.readTime}</span>
                    </div>
                  </div>

                  {/* Scientific Indication callout */}
                  <div className="bg-primary/5 p-4 rounded-lg border border-primary/10 flex gap-3 items-start">
                    <FlaskConical className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                    <div>
                      <h4 className="text-xs font-bold text-primary uppercase tracking-wider">Clinical Insight Summary</h4>
                      <p className="text-xs text-on-surface-variant leading-relaxed mt-1">
                        {selectedArticle.summary}
                      </p>
                    </div>
                  </div>

                  {/* Body Paragraphs */}
                  <div className="space-y-4 text-sm text-on-surface-variant leading-relaxed">
                    {selectedArticle.content.map((p, idx) => (
                      <p key={idx}>{p}</p>
                    ))}
                  </div>

                  {/* Disclaimer */}
                  <div className="bg-secondary-container/20 p-4 rounded-lg border border-outline-variant text-[11px] text-text-muted italic">
                    Disclaimer: This article is intended solely for scientific reference and medical education. Alloes formulations are clinical-grade and should be used according to standard directions or on advice of a dermatologist/physician.
                  </div>
                </motion.article>
              )}
            </div>

            {/* Footer */}
            <div className="p-4 bg-secondary-container/10 border-t border-outline-variant text-center text-[10px] text-text-muted">
              © 2026 Alloes Pharmaceuticals Research Division. Standardized clinical protocols verified in laboratory trials.
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
}
